# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'ZFDownload' do
pod 'ASIHTTPRequest', :git => 'https://github.com/p363796822/asi-http-request.git'
end

target 'ZFDownloadTests' do

end

target 'ZFDownloadUITests' do

end

